plugins {
    id 'dh-loader'
}

unimined.minecraft {
    cleanroom {
        loader gradle.ext.cleanroom_loader_version
        useToolchains = false
        accessTransformer project(":common").file("src/main/resources/${gradle.ext.accessWidenerVersion}.distanthorizons_at.cfg")
        runs.all {
            systemProperty("crl.dev.mixin", "${mod_id}.default.mixin.json,${mod_id}.mod.mixin.json")
            systemProperty("fml.coreMods.load", "com.seibel.distanthorizons.cleanroom.DistantHorizonsLoadingPlugin")
        }
    }
}