plugins {
    id 'dh-loader'
}

unimined.minecraft {
    minecraftForge {
        loader gradle.ext.forge_version
        useToolchains = false
        accessTransformer project(":common").file("src/main/resources/${gradle.ext.accessWidenerVersion}.distanthorizons_at.cfg")
        mixinConfig("DistantHorizons.forgevintage.mixins.json")
    }

    mods {
        //remap(configurations.modCompileOnly)
        remap(configurations.modRuntimeOnly)
    }
}

/*// set the java version for running is necessary for older MC versions
// that don't support the latest java version
def launcher = javaToolchains.launcherFor {
    languageVersion.set(JavaLanguageVersion.of(rootProject.java_version as Integer))
}
runClient.javaLauncher.set(launcher)
runServer.javaLauncher.set(launcher)*/
