plugins {
    id 'root'
    id 'io.github.pacifistmc.forgix' version '2.+' apply false
}

if (gradle.ext.minecraft_version != "1.7.10") {
    apply plugin: 'io.github.pacifistmc.forgix'

    forgix {
        int loaderCount = 0
        String modLoaders = ""
        ((String) gradle.builds_for)
            .split(",")
            .each { loader ->
                def loaderName = loader.trim()
                if (modLoaders != "") modLoaders += "-"
                modLoaders += loaderName
                loaderCount++
            }
        autoRun = (loaderCount > 1)
        archiveClassifier = modLoaders
    }
}
