plugins {
    id 'unimined-cleanroom'
}

// Mojang removed ARM LWJGL natives, which causes CI to fail for 1.12.2. Note: this means we cannot build on ARM CPUs right now.
configurations.configureEach {
    incoming.beforeResolve {
        dependencies.withType(ExternalDependency).each { dep ->
            if (dep.group == 'org.lwjgl') {
                dep.artifacts.removeIf {
                    it.classifier?.contains('arm')
                }
            }
        }
    }
}

// ==================== Mod Dependency Helper ====================

def addMod(path, enabled) {
    if (enabled == "2")
        dependencies { modImplementation(path) }
    else if (enabled == "1")
        dependencies { modCompileOnly(path) }
}


// ==================== Dependencies ====================

dependencies {
    addMod('curse.maven:autoreglib-250363:2746011', rootProject.enable_quark)
    addMod('curse.maven:quark-243121:2924091', rootProject.enable_quark)
    
    addMod('curse.maven:serene-seasons-291874:2799213', rootProject.enable_serene_seasons)
    
    addMod('curse.maven:cofh-core-69162:2920433', rootProject.enable_thermal_dynamics)
    addMod('curse.maven:thermal-dynamics-227443:2920505', rootProject.enable_thermal_dynamics)
}


// ==================== Tasks ====================

task deleteResources(type: Delete) {
    delete file("build/resources/main")
}

processResources {
    rename '(.+_at.cfg)', 'META-INF/$1'
    dependsOn(copyCoreResources)
    dependsOn(convertJsonToLang)
    // dependsOn(copyCommonLoaderResources)
}

tasks.named('runClient') {
    dependsOn(copyCoreResources)
    // dependsOn(copyCommonLoaderResources)
    finalizedBy(deleteResources)
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}


