plugins {
    id 'unimined-legacyforge'
}

repositories {
    maven {
        name "GTNH Maven"
        url "https://nexus.gtnewhorizons.com/repository/public/" // UniMixins
    }
    maven {
        name = "mavenpattern"
        url = "https://mvn.falsepattern.com/releases" // RPLE
        content {
            includeGroup "com.falsepattern"
        }
    }
}

// ==================== Mod Dependency Helper ====================

def addMod(path, enabled) {
    if (enabled == "2")
        dependencies { modImplementation(path) }
    else if (enabled == "1")
        dependencies { modCompileOnly(path) }
}


// ==================== Dependencies ====================

dependencies {
    modCompileOnly "com.github.GTNewHorizons:Hodgepodge:2.7.13:dev"
    modCompileOnly "com.github.GTNewHorizons:GTNHLib:0.6.11:dev"
    modCompileOnly("com.github.GTNewHorizons:GT5-Unofficial:5.09.51.469:dev") { transitive = false }
    modCompileOnly "com.github.GTNewHorizons:Angelica:2.1.5:dev"
    modCompileOnly "com.falsepattern:rple-mc1.7.10:2.1.0:api"

    modRuntimeOnly('curse.maven:zume-927564:7983502')
    
    implementation "io.github.legacymoddingmc:unimixins:0.1.23:dev"
/*
    modImplementation("com.github.GTNewHorizons:lwjgl3ify:2.1.5") {
        exclude group: "io.github.legacymoddingmc", module: "unimixins"
    }
    modImplementation("com.github.GTNewHorizons:lwjgl3ify:2.1.5:forgePatches") {
        exclude group: "io.github.legacymoddingmc", module: "unimixins"
    }
    def lwjglVersion = "3.3.3"
    implementation "org.lwjgl:lwjgl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-stb:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl:${lwjglVersion}:natives-windows"
    implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}:natives-windows"
    implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}:natives-windows"
    implementation "org.lwjgl:lwjgl-stb:${lwjglVersion}:natives-windows"
*/

}

// ==================== Tasks ====================

task deleteResources(type: Delete) {
    delete file("build/resources/main")
}

processResources {
    dependsOn(copyCoreResources)
    dependsOn(convertJsonToLang)
    // dependsOn(copyCommonLoaderResources)

    from(project(":common").file("src/main/resources/${gradle.ext.accessWidenerVersion}.distanthorizons_at.cfg")) {
        into 'META-INF'
    }
}

tasks.named('runClient') {
    dependsOn(copyCoreResources)
    // dependsOn(copyCommonLoaderResources)
    finalizedBy(deleteResources)
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}


