# 1.7.10 version
java_version=8
minecraft_version=1.7.10
parchment_version=
compatible_minecraft_versions=["1.7.10"]
accessWidenerVersion=1_7_10
builds_for=forgearchaic
embed_joml=true

# Netty
netty_version=4.0.23.Final

# LWJGL
lwjgl_version=2.9.3

# Forge loader
forge_version=10.13.4.1614-1.7.10
    # Neo not used but the variable still needs to be defined to make gradle happy
    neoforge_version_range=[*,)
    
    # Forge mod versions
    
    # Forge mod run
    # 0 = Don't enable and don't run
    # 1 = Can be referenced in code but doesn't run
    # 2 = Can be referenced in code and runs in client
    enable_angelica=1

fabric_loader_version=
fabric_api_version=
    # Fabric mod versions
    
    fabric_incompatibility_list={}
    fabric_recommend_list={}
    
    # Fabric mod run
    # 0 = Don't enable and don't run
    # 1 = Can be referenced in code but doesn't run
    # 2 = Can be referenced in code and runs in client